# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: learn-cts-example
# Description: Example task with two services

terraform {
  required_version = ">= 0.13.0, < 1.2.0"
  backend "consul" {
    address = "localhost:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}


# Example task with two services
module "learn-cts-example" {
  source   = "findkim/print/cts"
  version  = "0.1.0"
  services = var.services
}
